---
name: CI

on:
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.9

      - name: Update repositories
        run: |
          sudo apt update

      - name: Install Apptainer dependencies
        run: |
          sudo apt-get install -f -y build-essential libssl-dev uuid-dev squashfs-tools libseccomp-dev cryptsetup-bin libgpgme-dev

      - name: Install LaTeX dependencies
        run: |
          sudo apt-get install -f -y texlive-latex-extra latexmk

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Install Sphinx
        run: |
          pip install --user rstcheck
          # docutils<0.21 is a temporary downgrade to fix a compiling issue
          # see https://github.com/CrossNox/m2r2/issues/68
          # Note any change here also has to go into publish.yml
          # and in apptainer-admindocs publish.yml
          pip install --user --upgrade --upgrade-strategy eager "docutils<0.21" setuptools sphinx sphinx-rtd-theme restructuredtext_lint pygments m2r2

      - name: Lint rst
        run: |
          set -x
          mkdir _tmp/
          python3 copyreplace.py _tmp/ *.rst
          rstcheck --ignore-languages c,c++ --report-level warning _tmp/*
          rm -fr _tmp/

      - name: Build web documentation
        run: |
          make html

      - name: Build PDF documentation
        run: |
          make latexpdf

      - name: Build EPUB documentation
        run: |
          make epub
